# Default web server if no Ingress rule applies.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nameprefix" . }}-default-http-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: {{ template "nameprefix" . }}-default-http-backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nameprefix" . }}-default-http-backend
spec:
  revisionHistoryLimit: 3
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "nameprefix" . }}-default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: default-http-backend
          image: gcr.io/google_containers/defaultbackend:1.0
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            # Security hack, see https://github.com/kubernetes/kubernetes/issues/16779
            - name: no-service-account
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: no-service-account
          emptyDir: {}

